name: openttd-casept
version: '1.7.0'
summary: OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe 
description: |
  OpenTTD is an open source simulation game based upon the popular
  Microprose game Transport Tycoon Deluxe, written by Chris Sawyer.
  It attempts to mimic the original game as closely as possible while extending it with new features.
  This is an unofficial snap containing both the engine and open* asset packs.

grade: stable 
confinement: strict
apps:
  openttd:
    command: desktop-launch $SNAP/opt/openttd/openttd
    plugs: [network, network-bind, x11, opengl, pulseaudio, alsa]


parts:
  openttd:
    plugin: autotools
    source: https://binaries.openttd.org/releases/1.7.0/openttd-1.7.0-source.tar.gz
    build-packages:
      - build-essential
      - pkg-config
      - libsdl1.2-dev
      - patch
      - zlib1g-dev
      - liblzo2-dev
      - liblzma-dev
      - libfontconfig1-dev
      - libicu-dev
    stage-packages:
      - libicu55 
      - libsdl1.2debian 
      - fontconfig
      - libfreetype6
      - libpng12-0
      - liblzo2-2
      - liblzma5
      - zlib1g
      - libpulse0
      - libgl1-mesa-dri
      - timidity
      - freepats
    #TODO: Clean this up
    build: |
      ./configure
      make -j$(nproc)
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/openttd/
      cp -r bin/* $SNAPCRAFT_PART_INSTALL/opt/openttd/
    after: [desktop-glib-only]

  opengfx:
    plugin: make
    source: https://binaries.openttd.org/extra/opengfx/0.5.2/opengfx-0.5.2-source.tar.xz
    build-packages:
      # Yes, we do indeed need GIMP
      - gimp
      - nml
      - dos2unix
      - grfcodec
      - tar
      - gcc
    build: make
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opengfx/
      cp -r opengfx-0.5.2/* $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opengfx/
    after: [openttd]

  opensfx:
    plugin: make
    source: https://binaries.openttd.org/extra/opensfx/0.2.3/opensfx-0.2.3-source.tar.gz 
    build-packages:
      - catcodec
    build: make
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opensfx/
      cp opensfx.cat $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opensfx/
      cp opensfx.obs $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opensfx/
      cp docs/* $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/opensfx/
    after: [openttd]

  openmsx:
    plugin: make
    source: https://binaries.openttd.org/extra/openmsx/0.3.1/openmsx-0.3.1-source.tar.gz 
    build-packages:
      - dos2unix
      - python
    build: make
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/openmsx/
      cp openmsx.obm $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/openmsx/
      cp src/* $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/openmsx/
      cp docs/* $SNAPCRAFT_PART_INSTALL/opt/openttd/baseset/openmsx/
    after: [openttd]

