name: openttd-server
adopt-info: openttd-server
summary: OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: >
  OpenTTD is an open source simulation game based upon the popular
  Microprose game Transport Tycoon Deluxe, written by Chris Sawyer.
  It attempts to mimic the original game as closely as possible while
  extending it with new features.
  This is an unofficial snap containing both the engine and open* asset packs.

  * Upstream project: https://www.openttd.org/
  * Snapcraft.yaml repository: https://github.com/diddlesnaps/openttd

grade: stable
confinement: strict
base: core18

apps:
  openttd-server:
    command: usr/games/openttd/openttd -D
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  openttd-server:
    plugin: autotools
    source: https://github.com/OpenTTD/OpenTTD.git
    override-pull: |
      snapcraftctl pull
      VERSION="$(git tag --list --sort=version:refname | grep -v -E '(-RC|beta)' | tail -n1)"
      git checkout "$VERSION"
      snapcraftctl set-version "$VERSION"
      sed -E -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/openttd.png|' media/openttd.desktop
    configflags:
      - --prefix=/usr
      - --binary-dir=games/openttd
      - --data-dir=games/openttd
      - --install-dir=$SNAPCRAFT_PART_INSTALL
      - --enable-lto
      - --enable-strip
      - --with-fluidsynth
      - --with-sdl=sdl2
      - --with-zlib
      - --with-liblzma
      - --with-liblzo2
      - --with-libpng
      - --with-freetype
      - --with-fontconfig
      - --with-icu
      - --with-icu-layout
      - --with-iconv
    build-packages:
      - g++
      - patch
      - libfluidsynth-dev
      - libfontconfig1-dev
      - libglu1-mesa-dev
      - libicu-dev
      - liblzma-dev
      - liblzo2-dev
      - libsdl2-dev
      - zlib1g-dev
    stage-packages:
      - fontconfig
      - freepats
      - libfluidsynth1
      - libfreetype6
      - libglu1-mesa
      - libicu-le-hb0
      - libicu60
      - libiculx60
      - liblzma5
      - liblzo2-2
      - libsdl2-2.0-0
      - timidity

  opengfx:
    plugin: dump
    source: https://cdn.openttd.org/opengfx-releases/0.6.0/opengfx-0.6.0-all.zip
    organize:
      opengfx-*.tar: usr/games/openttd/baseset/

  opensfx:
    plugin: dump
    source: https://cdn.openttd.org/opensfx-releases/0.2.3/opensfx-0.2.3-all.zip
    organize:
      opensfx-*: usr/games/openttd/baseset/

  openmsx:
    plugin: dump
    source: https://cdn.openttd.org/openmsx-releases/0.3.1/openmsx-0.3.1-all.zip
    organize:
      openmsx-*: usr/games/openttd/baseset/
