name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/openttd/openttd/releases/latest | \
          jq -r ".tag_name" > openttd-version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Zoltan Tamas Vajda'
          git config --global user.email '38247263+zoltantamasvajda@users.noreply.github.com'
          git commit -am "New OpenTTD version"
          git push
